version: '2'

services:
   db:
     restart: always
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=magento
     volumes:
       - ./project/db:/var/lib/mysql

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento2v3
     restart: always
     ports:
       - "2222:22"
       - "8080:80"
       - "443:443"
     environment:
       MAGENTO_DB_HOST: db:3306
     volumes:
       - ./project/website:/var/www
       - ./project/nginxconf:/etc/nginx/sites-available

   redis:
     image: redis
     restart: always

   varnish:
     image: gesmogast/varnish
     restart: always
     ports:
       - "80:80"
     links:
       - magento:testmagento.org
     volumes:
       - ./project/varnishconf:/etc/varnish
     environment:
       - CACHE_SIZE 64m
       - VARNISHD_PARAMS -p default_ttl=3600 -p default_grace=3600
       - VCL_CONFIG /etc/varnish/conf.d/default.vcl
