version: '2'

services:
   db:
     image: gesmogast/percona:5.6
     restart: always
     ports:
       - "3306:3306"

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento1v1
     restart: always
     ports:
       - "80:80"
