version: '2'

services:
   db:
     restart: always
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=magento
     volumes:
       - ./project/db:/var/lib/mysql

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento1v2
     restart: always
     ports:
       - "80:80"
       - "3322:22"
     volumes:
       - ./project/website:/var/www
       - ./project/nginxconf:/etc/nginx/sites-available
