version: '2'

services:
   db:
     image: gesmogast/mariadb:wordpress
     restart: always

   wordpress:
     depends_on:
       - db
     image: gesmogast/wordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
