version: '2'

services:
   db:
     image: gesmogast/mariadb:magento
     restart: always

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento
     restart: always
     ports:
       - "80"
     environment:
       - MAGENTO_DB_HOST=db:3306
       - VIRTUAL_HOST=testmagento.org

   redis:
     image: redis
     restart: always

   nginx-proxy:
     image: jwilder/nginx-proxy:latest
     container_name: nginx-proxy
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
