version: '2'

services:
   db:
     image: gesmogast/percona:5.6
     restart: always
     ports:
       - "3306:3306"    

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento2v2
     restart: always
     ports:
       - "80:80"
       - "443:443"
     environment:
       MAGENTO_DB_HOST: db:3306
     volumes:
       - /vagrant/project/website:/var/www
       - /vagrant/project/nginxconf:/etc/nginx/sites-available
