version: '2'

services:
   nginx-reverse-proxy:
     image: nginx
     container_name: nginx-reverse-proxy
     ports:
       - "192.168.20.91:80:80"
       - "192.168.20.91:443:443"
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
