version: '2'

services:
   db:
     image: gesmogast/percona:5.6
     restart: always

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento2
     restart: always
     ports:
       - "80:80"
     environment:
       MAGENTO_DB_HOST: db:3306

   redis:
     image: redis
     restart: always

