version: '2'

services:
   db:
     image: gesmogast/mariadb:magento
     restart: always

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento
     ports:
       - "80:80"
     restart: always
     environment:
       MAGENTO_DB_HOST: db:3306
