version: '2'

services:
   db:
     image: gesmogast/percona:5.6
     restart: always
     ports:
       - "3306:3306"    

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento2v1
     restart: always
     ports:
       - "85:80"
       - "444:443"
     environment:
       MAGENTO_DB_HOST: db:3306
