version: '2'

services:
   db:
     restart: always
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=magento
     volumes:
       - ./project/db:/var/lib/mysql

   magento:
     depends_on:
       - db
     image: gesmogast/nginx:magento2v3
     restart: always
     ports:
       - "2230:22"
       - "80:80"
       - "444:443"
     environment:
       - MAGENTO_DB_HOST=db:3306
     volumes:
       - ./project/website:/var/www
       - ./project/nginxconf:/etc/nginx/sites-available

   php-fpm:
     image: gesmogast/php7.0-fpm:v2
     expose:
       - "9000"
     ports:
       - "2253:22"
     links:
       - magento
     volumes_from:
       - magento

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - "8080:80"
     environment:
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       PMA_HOST: db
