version: '2'

services:
   db1:
     image: gesmogast/mariadb:wordpress
     restart: always

   db2:
     image: gesmogast/mariadb:wordpress
     restart: always
   
   db3:
     image: gesmogast/mariadb:wordpress
     restart: always

   wordpress:
     depends_on:
       - db1
       - db2
       - db3
     image: gesmogast/wordpress
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db1:3306
